# This file contains the configuration settings for your Redwood app.
# This file is also what makes your Redwood app a Redwood app.
# If you remove it and try to run `yarn rw dev`, you'll get an error.
#
# For the full list of options, see the "App Configuration: redwood.toml" doc:
# https://redwoodjs.com/docs/app-configuration-redwood-toml

[web]
  title = "Swordy Bot"
  port = 8910
  host = "0.0.0.0"
  apiProxyPath = "/.redwood/functions"
  includeEnvironmentVariables = [
    # Discord
    'DISCORD_INVITE_LINK',
    'DISCORD_PUBLIC_CLIENT_ID',
  ]
[api]
  port = 8911
  includeEnvironmentVariables = [
    # Auth
    'ETHEREUM_JWT_SECRET',
    # Ethereum
    'XDAI_RPC',
    'INFURA_ID',
    'MATIC_RPC',
    'OPTIMISM_RPC',
    'MUMBAI_RPC',
    'BSC_MAINNET_RPC',
    'BSC_TESTNET_RPC',
    'UBIQ_RPC',
    # Oauth
    'PUBLIC_REDIRECT_URL',
    # Sentry.io
    'SENTRY_DSN',
    # Discord
    'DISCORD_PUBLIC_CLIENT_ID',
    'DISCORD_CLIENT_SECRET',
    'DISCORD_BOT_TOKEN',
    # Database
    'DATABASE',
    'REDWOOD_SECURE_SERVICES' ]
[browser]
  open = true
[experimental]
  esbuild = false
  useEnvelop = true
