name: Repo sync (for Vercel deployments)

on:
  push:
    branches: [master, dev]
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync-master
        uses: wei/git-sync@v3
        with:
          source_repo: 'git@github.com:oneclickdapp/swordy-bot-v2.git'
          source_branch: 'master'
          destination_repo: 'git@github.com:pi0neerpat/swordy-bot-v2.git'
          destination_branch: 'master'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: git-sync-dev
        uses: wei/git-sync@v3
        with:
          source_repo: 'git@github.com:oneclickdapp/swordy-bot-v2.git'
          source_branch: 'dev'
          destination_repo: 'git@github.com:pi0neerpat/swordy-bot-v2.git'
          destination_branch: 'dev'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
