name: Repo sync (for Vercel deployments)

on:
  push:
    branches: [master, dev]
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync-master
        uses: wei/git-sync@v3
        with:
          source_repo: 'oneclickdapp/swordy-bot-v2'
          source_branch: 'master'
          destination_repo: 'pi0neerpat/swordy-bot-v2'
          destination_branch: 'master'
      - name: git-sync-dev
        uses: wei/git-sync@v3
        with:
          source_repo: 'oneclickdapp/swordy-bot-v2'
          source_branch: 'dev'
          destination_repo: 'pi0neerpat/swordy-bot-v2'
          destination_branch: 'dev'
